# Generated by Django 5.1.1 on 2024-09-13 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.departement')),
            ],
        ),
        migrations.CreateModel(
            name='CoursExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('type', models.CharField(choices=[('cours', 'Cours'), ('exercice', 'Exercice')], max_length=10)),
                ('description', models.TextField()),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.niveau')),
            ],
        ),
    ]
