# Generated by Django 5.1.1 on 2024-09-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='faculte',
            field=models.CharField(choices=[('scientifique', 'Faculté des Sciences'), ('litteraire', 'Faculté des Lettres')], default='Faculte par defaut', max_length=15),
            preserve_default=False,
        ),
    ]
